spring:
  application:
    name: todo-list
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: todolist-secret-key-123456789012345678901234567890
    expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /todo-list
